# Generated by Django 5.2.5 on 2025-08-21 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('rainfall', models.FloatField()),
                ('wind_speed', models.FloatField()),
                ('condition', models.CharField(max_length=100)),
                ('uv_index', models.FloatField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(default='API', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Weather History',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
