from django import template
from django.utils import translation

register = template.Library()

# Simple translation dictionary
TRANSLATIONS = {
    'en': {
        'PaddySense': 'PaddySense',
        'Home': 'Home',
        'Dashboard': 'Dashboard',
        'Weather': 'Weather',
        'Analytics': 'Analytics',
        'Recommendations': 'Recommendations',
        'About': 'About',


        'Language': 'Language',
        'English': 'English',
        'Tamil': 'Tamil',
        'Welcome to PaddySense': 'Welcome to PaddySense',
        'Intelligent Farming Platform': 'Intelligent Farming Platform',
        'Empowering farmers with AI-driven insights, real-time monitoring, and data-driven recommendations for optimal crop management.': 'Empowering farmers with AI-driven insights, real-time monitoring, and data-driven recommendations for optimal crop management.',
        'Get Started': 'Get Started',
        'Learn More': 'Learn More',
        'Weather Insights': 'Weather Insights',
        'Real-time weather data and forecasts to optimize farming decisions.': 'Real-time weather data and forecasts to optimize farming decisions.',
        'View Details': 'View Details',
        'Data Analytics': 'Data Analytics',
        'Comprehensive analytics and performance metrics for your farm.': 'Comprehensive analytics and performance metrics for your farm.',
        'AI Recommendations': 'AI Recommendations',
        'AI-powered suggestions for optimal crop management and yield improvement.': 'AI-powered suggestions for optimal crop management and yield improvement.',
        'Crop Monitoring': 'Crop Monitoring',
        'Monitor crop health, growth stages, and environmental conditions in real-time.': 'Monitor crop health, growth stages, and environmental conditions in real-time.',
        'Smart Irrigation': 'Smart Irrigation',
        'Automated irrigation systems that respond to soil moisture and weather conditions.': 'Automated irrigation systems that respond to soil moisture and weather conditions.',
        'Expert Support': 'Expert Support',
        'Connect with agricultural experts and get personalized advice for your farm.': 'Connect with agricultural experts and get personalized advice for your farm.',
        'Social Media': 'Social Media',
        'Follow us on social media for the latest updates and farming tips.': 'Follow us on social media for the latest updates and farming tips.',
        'Facebook': 'Facebook',
        'Twitter': 'Twitter',
        'LinkedIn': 'LinkedIn',
        '© 2025 PaddySense. All rights reserved.': '© 2025 PaddySense. All rights reserved.',
        'Powered by AI Technology': 'Powered by AI Technology',
        'Current Weather': 'Current Weather',
        'Loading...': 'Loading...',
        'Humidity': 'Humidity',
        'Quick Stats': 'Quick Stats',
        'Crop Health': 'Crop Health',
        'Soil Temp': 'Soil Temp',
        'Moisture': 'Moisture',
        'Days Left': 'Days Left',
        'Select Location': 'Select Location',
        'Enter city name (e.g., Coimbatore, Madurai)': 'Enter city name (e.g., Coimbatore, Madurai)',
        'Search': 'Search',
        'Quick Select': 'Quick Select',
        'Search Any Location Worldwide': 'Search Any Location Worldwide',
        'Search Location': 'Search Location',
        'Type any city, country, or location (e.g., Tokyo, London, New York, Mumbai, Beijing, Paris, Dubai, Sydney)': 'Type any city, country, or location (e.g., Tokyo, London, New York, Mumbai, Beijing, Paris, Dubai, Sydney)',

    },
    'ta': {
        'PaddySense': 'பாடி சென்ஸ்',
        'Home': 'முகப்பு',
        'Dashboard': 'டாஷ்போர்டு',
        'Weather': 'வானிலை',
        'Analytics': 'பகுப்பாய்வு',
        'Recommendations': 'பரிந்துரைகள்',
        'About': 'பற்றி',


        'Language': 'மொழி',
        'English': 'ஆங்கிலம்',
        'Tamil': 'தமிழ்',
        'Welcome to PaddySense': 'பாடி சென்ஸுக்கு வரவேற்கிறோம்',
        'Intelligent Farming Platform': 'நுண்ணறிவு விவசாய தளம்',
        'Empowering farmers with AI-driven insights, real-time monitoring, and data-driven recommendations for optimal crop management.': 'செயற்கை நுண்ணறிவு அடிப்படையிலான நுண்ணறிவுகள், நேரலை கண்காணிப்பு மற்றும் உகந்த பயிர் மேலாண்மைக்கான தரவு அடிப்படையிலான பரிந்துரைகளுடன் விவசாயிகளை மேம்படுத்துகிறது.',
        'Get Started': 'தொடங்குங்கள்',
        'Learn More': 'மேலும் அறியுங்கள்',
        'Weather Insights': 'வானிலை நுண்ணறிவு',
        'Real-time weather data and forecasts to optimize farming decisions.': 'விவசாய முடிவுகளை உகந்தமயமாக்க நேரலை வானிலை தரவு மற்றும் முன்னறிவிப்புகள்.',
        'View Details': 'விவரங்களைக் காண்க',
        'Data Analytics': 'தரவு பகுப்பாய்வு',
        'Comprehensive analytics and performance metrics for your farm.': 'உங்கள் பண்ணைக்கான விரிவான பகுப்பாய்வு மற்றும் செயல்திறன் அளவீடுகள்.',
        'AI Recommendations': 'செயற்கை நுண்ணறிவு பரிந்துரைகள்',
        'AI-powered suggestions for optimal crop management and yield improvement.': 'உகந்த பயிர் மேலாண்மை மற்றும் மகசூல் மேம்பாட்டிற்கான செயற்கை நுண்ணறிவு அடிப்படையிலான பரிந்துரைகள்.',
        'Crop Monitoring': 'பயிர் கண்காணிப்பு',
        'Monitor crop health, growth stages, and environmental conditions in real-time.': 'பயிர் ஆரோக்கியம், வளர்ச்சி நிலைகள் மற்றும் சுற்றுச்சூழல் நிலைமைகளை நேரலையில் கண்காணிக்கவும்.',
        'Smart Irrigation': 'ஸ்மார்ட் நீர்ப்பாசனம்',
        'Automated irrigation systems that respond to soil moisture and weather conditions.': 'மண் ஈரப்பதம் மற்றும் வானிலை நிலைமைகளுக்கு துலங்கும் தானியங்கி நீர்ப்பாசன அமைப்புகள்.',
        'Expert Support': 'நிபுணர் ஆதரவு',
        'Connect with agricultural experts and get personalized advice for your farm.': 'விவசாய நிபுணர்களுடன் இணைந்து உங்கள் பண்ணைக்கான தனிப்பட்ட ஆலோசனையைப் பெறுங்கள்.',
        'Social Media': 'சமூக ஊடகங்கள்',
        'Follow us on social media for the latest updates and farming tips.': 'சமீபத்திய புதுப்பிப்புகள் மற்றும் விவசாய குறிப்புகளுக்கு சமூக ஊடகங்களில் எங்களைப் பின்தொடரவும்.',
        'Facebook': 'பேஸ்புக்',
        'Twitter': 'ட்விட்டர்',
        'LinkedIn': 'லிங்க்ட்இன்',
        '© 2025 PaddySense. All rights reserved.': '© 2025 பாடி சென்ஸ். அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை.',
        'Powered by AI Technology': 'செயற்கை நுண்ணறிவு தொழில்நுட்பத்தால் இயக்கப்படுகிறது',
        'Current Weather': 'தற்போதைய வானிலை',
        'Loading...': 'ஏற்றுகிறது...',
        'Humidity': 'ஈரப்பதம்',
        'Quick Stats': 'விரைவு புள்ளிவிவரங்கள்',
        'Crop Health': 'பயிர் ஆரோக்கியம்',
        'Soil Temp': 'மண் வெப்பநிலை',
        'Moisture': 'ஈரப்பதம்',
        'Days Left': 'மீதமுள்ள நாட்கள்',
        'Select Location': 'இருப்பிடத்தைத் தேர்ந்தெடுக்கவும்',
        'Enter city name (e.g., Coimbatore, Madurai)': 'நகரத்தின் பெயரை உள்ளிடவும் (எ.கா., கோயம்புத்தூர், மதுரை)',
        'Search': 'தேடு',
        'Quick Select': 'விரைவு தேர்வு',
        'Search Any Location Worldwide': 'உலகெங்கிலும் உள்ள எந்த இருப்பிடத்தையும் தேடுங்கள்',
        'Search Location': 'இருப்பிடத்தைத் தேடுங்கள்',
        'Type any city, country, or location (e.g., Tokyo, London, New York, Mumbai, Beijing, Paris, Dubai, Sydney)': 'எந்த நகரம், நாடு அல்லது இருப்பிடத்தையும் தட்டச்சு செய்யவும் (எ.கா., டோக்கியோ, லண்டன், நியூயார்க், மும்பை, பெய்ஜிங், பாரிஸ், துபாய், சிட்னி)',
        'Paddy Variety Recommendations': 'நெல் வகை பரிந்துரைகள்',
        'Top Recommended Paddy Varieties': 'சிறந்த நெல் வகைகள்',
        'Match': 'பொருத்தம்',
        'Temperature': 'வெப்பநிலை',
        'Duration': 'காலம்',
        'Yield': 'மகசூல்',
        'Features': 'அம்சங்கள்',
        'Planting Tips': 'நடவு குறிப்புகள்',
        'Fertilizer Tips': 'உர குறிப்புகள்',
        'Irrigation Tips': 'நீர்ப்பாசன குறிப்புகள்',
        'Temperature Analysis': 'வெப்பநிலை பகுப்பாய்வு',
        'Current': 'தற்போதைய',
        'Range': 'வரம்பு',
        'Status': 'நிலை',
        'Too Cold': 'மிகவும் குளிர்',
        'Cold': 'குளிர்',
        'Optimal': 'சிறந்த',
        'Warm': 'சூடான',
        'Too Hot': 'மிகவும் சூடான',
        'User Input': 'பயனர் உள்ளீடு',
        'Soil Temperature & Location Input': 'மண் வெப்பநிலை மற்றும் இருப்பிட உள்ளீடு',
        'Record your field data to get personalized recommendations': 'தனிப்பட்ட பரிந்துரைகளைப் பெற உங்கள் வயல் தரவை பதிவு செய்யவும்',
        'Enter Your Data': 'உங்கள் தரவை உள்ளிடவும்',
        'Field Name': 'வயல் பெயர்',
        'Soil Temperature (°C)': 'மண் வெப்பநிலை (°C)',
        'Save Data': 'தரவை சேமிக்கவும்',
        'Tips for Accurate Measurements': 'துல்லியமான அளவீடுகளுக்கான குறிப்புகள்',
        'Measure soil temperature at 10-15cm depth': 'மண் வெப்பநிலையை 10-15cm ஆழத்தில் அளவிடவும்',
        'Take readings in the morning for consistency': 'நிலைத்தன்மைக்காக காலையில் அளவீடுகளை எடுக்கவும்',
        'Record location coordinates if possible': 'முடிந்தால் இருப்பிட ஆயங்களை பதிவு செய்யவும்',
        'Take multiple readings and average them': 'பல அளவீடுகளை எடுத்து அவற்றின் சராசரியை கணக்கிடவும்',
        'Recent Data Entries': 'சமீபத்திய தரவு உள்ளீடுகள்',
        'Field': 'வயல்',
        'Temp (°C)': 'வெப்பநிலை (°C)',
        'Time': 'நேரம்',
        'No data recorded yet': 'இன்னும் தரவு பதிவு செய்யப்படவில்லை',
        'Start by entering your first measurement above!': 'மேலே உங்கள் முதல் அளவீட்டை உள்ளிடுவதன் மூலம் தொடங்கவும்!',
        'Why This Matters': 'இது ஏன் முக்கியமானது',
        'Crop Growth': 'பயிர் வளர்ச்சி',
        'Optimal temperature ranges for different crops': 'வெவ்வேறு பயிர்களுக்கான உகந்த வெப்பநிலை வரம்புகள்',
        'Irrigation': 'நீர்ப்பாசனம்',
        'Water needs vary with soil temperature': 'தண்ணீர் தேவைகள் மண் வெப்பநிலையுடன் மாறுபடும்',
        'Fertilizer': 'உரம்',
        'Nutrient uptake depends on soil conditions': 'ஊட்டச்சத்து உறிஞ்சுதல் மண் நிலைமைகளைப் பொறுத்தது',
        'Yield': 'மகசூல்',
        'Better data leads to better decisions': 'சிறந்த தரவு சிறந்த முடிவுகளுக்கு வழிவகுக்கும்',
        'Next Steps': 'அடுத்த படிகள்',
        'Record Data': 'தரவை பதிவு செய்யவும்',
        'Input your measurements regularly': 'உங்கள் அளவீடுகளை தவறாமல் உள்ளிடவும்',
        'Get Insights': 'நுண்ணறிவுகளைப் பெறவும்',
        'View personalized recommendations': 'தனிப்பட்ட பரிந்துரைகளைக் காண்க',
        'Track Progress': 'முன்னேற்றத்தை கண்காணிக்கவும்',
        'Monitor improvements over time': 'காலப்போக்கில் மேம்பாடுகளை கண்காணிக்கவும்',
        'Optimize': 'உகந்தமயமாக்கவும்',
        'Apply insights for better yields': 'சிறந்த மகசூலுக்கு நுண்ணறிவுகளைப் பயன்படுத்தவும்',
    },
    'si': {
        'PaddySense': 'වී අවබෝධය',
        'Home': 'මුල් පිටුව',
        'Dashboard': 'උපකරණ පුවරුව',
        'Weather': 'වැසි අවස්ථාව',
        'Analytics': 'විශ්ලේෂණ',
        'Recommendations': 'නිර්දේශ',
        'About': 'ගැන',
        'Language': 'භාෂාව',
        'English': 'ඉංග්‍රීසි',
        'Tamil': 'දෙමළ',
        'Sinhala': 'සිංහල',
        'Welcome to PaddySense': 'වී අවබෝධයට සාදරයෙන් පිළිගනිමු',
        'Intelligent Farming Platform': 'බුද්ධිමත් කෘෂිකර්ම වේදිකාව',
        'Empowering farmers with AI-driven insights, real-time monitoring, and data-driven recommendations for optimal crop management.': 'AI-ධාවිත තීක්ෂ්ණ බුද්ධිය, තාත්වික කාල නිරීක්ෂණ සහ ප්‍රශස්ත බෝග කළමනාකරණය සඳහා දත්ත-ධාවිත නිර්දේශ සමඟ ගොවීන් බලවත් කිරීම.',
        'Get Started': 'ආරම්භ කරන්න',
        'Learn More': 'තවත් දැනගන්න',
        'Weather Insights': 'වැසි අවස්ථා තීක්ෂ්ණ බුද්ධිය',
        'Real-time weather data and forecasts to optimize farming decisions.': 'කෘෂිකර්ම තීරණ ප්‍රශස්ත කිරීම සඳහා තාත්වික කාල වැසි අවස්ථා දත්ත සහ පුරෝකථන.',
        'View Details': 'විස්තර බලන්න',
        'Data Analytics': 'දත්ත විශ්ලේෂණ',
        'Comprehensive analytics and performance metrics for your farm.': 'ඔබේ ගොවිපල සඳහා සවිස්තරාත්මක විශ්ලේෂණ සහ කාර්යක්ෂමතා මිනුම්.',
        'AI Recommendations': 'AI නිර්දේශ',
        'AI-powered suggestions for optimal crop management and yield improvement.': 'ප්‍රශස්ත බෝග කළමනාකරණය සහ ඵලදායිතා වැඩිදියුණු කිරීම සඳහා AI-ධාවිත යෝජනා.',
        'Crop Monitoring': 'බෝග නිරීක්ෂණ',
        'Monitor crop health, growth stages, and environmental conditions in real-time.': 'බෝග සෞඛ්‍යය, වර්ධන අවධි සහ පරිසර තත්වයන් තාත්වික කාලයෙහි නිරීක්ෂණය කරන්න.',
        'Smart Irrigation': 'බුද්ධිමත් ජලය ලබාදීම',
        'Automated irrigation systems that respond to soil moisture and weather conditions.': 'පස තෙතමනය සහ වැසි අවස්ථාවන්ට ප්‍රතිචාර දක්වන ස්වයංක්‍රීය ජලය ලබාදීමේ පද්ධති.',
        'Expert Support': 'විශේෂඥ සහාය',
        'Connect with agricultural experts and get personalized advice for your farm.': 'කෘෂිකර්ම විශේෂඥයින් සමඟ සම්බන්ධ වී ඔබේ ගොවිපල සඳහා පුද්ගලික උපදෙස් ලබා ගන්න.',
        'Social Media': 'සමාජ මාධ්‍ය',
        'Follow us on social media for the latest updates and farming tips.': 'නවතම යාවත්කාලීන කිරීම් සහ කෘෂිකර්ම උපදෙස් සඳහා සමාජ මාධ්‍යවල අපව අනුගමනය කරන්න.',
        'Facebook': 'ෆේස්බුක්',
        'Twitter': 'ට්විටර්',
        'LinkedIn': 'ලින්ක්ඩින්',
        '© 2025 PaddySense. All rights reserved.': '© 2025 වී අවබෝධය. සියලුම අයිතිවාසිකම් රක්ෂිතයි.',
        'Powered by AI Technology': 'AI තාක්ෂණයෙන් බලගන්වා ඇත',
        'Current Weather': 'වර්තමාන වැසි අවස්ථාව',
        'Loading...': 'පූරණය වෙමින්...',
        'Humidity': 'ආර්ද්‍රතාව',
        'Quick Stats': 'ඉක්මන් සංඛ්‍යාලේඛන',
        'Crop Health': 'බෝග සෞඛ්‍යය',
        'Soil Temp': 'පස උෂ්ණත්වය',
        'Moisture': 'තෙතමනය',
        'Days Left': 'ඉතිරි දින',
        'Select Location': 'ස්ථානය තෝරන්න',
        'Enter city name (e.g., Coimbatore, Madurai)': 'නගරයේ නම ඇතුළත් කරන්න (උදා., කොයිම්බතෝර්, මධුරායි)',
        'Search': 'සොයන්න',
        'Quick Select': 'ඉක්මන් තේරීම',
        'Search Any Location Worldwide': 'ලෝකයේ ඕනෑම ස්ථානයක් සොයන්න',
        'Search Location': 'ස්ථානය සොයන්න',
        'Type any city, country, or location (e.g., Tokyo, London, New York, Mumbai, Beijing, Paris, Dubai, Sydney)': 'ඕනෑම නගරයක්, රටක් හෝ ස්ථානයක් ටයිප් කරන්න (උදා., ටෝකියෝ, ලන්ඩන්, නිව්යෝර්ක්, මුම්බායි, බෙයිජිං, පැරිස්, දුබායි, සිඩ්නි)',
        'Crop Forecasting': 'බෝග අනාවැකි',
        'Paddy Variety Recommendations': 'වී වර්ග බලපොරොත්තු',
        'Top Recommended Paddy Varieties': 'ඉහළම නිර්දේශිත වී වර්ග',
        'Match': 'ගැලපීම',
        'Temperature': 'උෂ්ණත්වය',
        'Duration': 'කාලසීමාව',
        'Yield': 'ඵලදායිතාව',
        'Features': 'විශේෂාංග',
        'Planting Tips': 'වැපිරීමේ උපදෙස්',
        'Fertilizer Tips': 'සාර උපදෙස්',
        'Irrigation Tips': 'වාරිමාර්ග උපදෙස්',
        'Temperature Analysis': 'උෂ්ණත්ව විශ්ලේෂණය',
        'Current': 'වර්තමාන',
        'Range': 'පරාසය',
        'Status': 'තත්වය',
        'Too Cold': 'ඉතා සීතල',
        'Cold': 'සීතල',
        'Optimal': 'ප්‍රශස්ත',
        'Warm': 'උණුසුම්',
        'Too Hot': 'ඉතා උණුසුම්',
        'Soil Temperature & Location Input': 'පස උෂ්ණත්වය සහ ස්ථාන ආදානය',
        'Record your field data to get personalized recommendations': 'පුද්ගලික නිර්දේශ ලබා ගැනීමට ඔබේ ක්ෂේත්‍ර දත්ත පටිගත කරන්න',
        'Enter Your Data': 'ඔබේ දත්ත ඇතුළත් කරන්න',
        'Location': 'ස්ථානය',
        'Field Name': 'ක්ෂේත්‍ර නම',
        'Soil Temperature (°C)': 'පස උෂ්ණත්වය (°C)',
        'Save Data': 'දත්ත සුරකින්න',
        'Tips for Accurate Measurements': 'නිවැරදි මිනුම් සඳහා උපදෙස්',
        'Measure soil temperature at 10-15cm depth': 'පස උෂ්ණත්වය 10-15cm ගැඹුරින් මනින්න',
        'Take readings in the morning for consistency': 'ස්ථාවරත්වය සඳහා උදෑසන කියවීම් ගන්න',
        'Record location coordinates if possible': 'හැකි නම් ස්ථාන ඛණ්ඩාංක පටිගත කරන්න',
        'Take multiple readings and average them': 'බහු කියවීම් ගෙන ඒවා සාමාන්‍ය කරන්න',
        'Recent Data Entries': 'මෑත දත්ත ඇතුළත් කිරීම්',
        'Field': 'ක්ෂේත්‍රය',
        'Temp (°C)': 'උෂ්ණත්වය (°C)',
        'Time': 'වේලාව',
        'Decide the vegetable crop according to the sales forecast': 'අලෙවි අනාවැකිය අනුව එළවලු බෝගය තීරණය කරන්න',
        'Weather & Crop Analysis': 'වැසි අවස්ථාව සහ බෝග විශ්ලේෂණය',
        'Current Location': 'වර්තමාන ස්ථානය',
        'Current Weather': 'වර්තමාන වැසි අවස්ථාව',
        'Rainfall': 'වැසි',
        'Condition': 'තත්වය',
        'Recommended Crops': 'නිර්දේශිත බෝග',
        '5-Day Weather Forecast': '5-දින වැසි අවස්ථා පුරෝකථන',
        'Mobile App': 'ජංගම යෙදුම',
        'Language Selection': 'භාෂා තේරීම',
        'Sales Forecast System': 'අලෙවි අනාවැකි පද්ධතිය',
        'Understand the sales fate of your favorite crop by looking at the emoji faces': 'ඉමොජි මුහුණු බලා ඔබේ ප්‍රියතම බෝගයේ අලෙවි අනාවැකිය තේරුම් ගන්න',
        'Quick Actions': 'ඉක්මන් ක්‍රියා',
        'Get Paddy Recommendations': 'වී නිර්දේශ ලබා ගන්න',
        'Check Weather': 'වැසි අවස්ථාව පරීක්ෂා කරන්න',
        'View Dashboard': 'උපකරණ පුවරුව බලන්න',
        'Department of Agriculture Style Interface': 'කෘෂිකර්ම දෙපාර්තමේන්තුවේ විලාසයේ අතුරුමුහුණත',
        'Professional crop forecasting system with Sinhala language support': 'සිංහල භාෂා සහාය සහිත වෘත්තීය බෝග අනාවැකි පද්ධතිය',
        'User Input': 'පරිශීලක ආදානය',
        'Soil Temperature & Location Input': 'පස උෂ්ණත්වය සහ ස්ථාන ආදානය',
        'Record your field data to get personalized recommendations': 'පුද්ගලික නිර්දේශ ලබා ගැනීමට ඔබේ ක්ෂේත්‍ර දත්ත පටිගත කරන්න',
        'Enter Your Data': 'ඔබේ දත්ත ඇතුළත් කරන්න',
        'Field Name': 'ක්ෂේත්‍ර නම',
        'Soil Temperature (°C)': 'පස උෂ්ණත්වය (°C)',
        'Save Data': 'දත්ත සුරකින්න',
        'Tips for Accurate Measurements': 'නිවැරදි මිනුම් සඳහා උපදෙස්',
        'Measure soil temperature at 10-15cm depth': 'පස උෂ්ණත්වය 10-15cm ගැඹුරින් මනින්න',
        'Take readings in the morning for consistency': 'ස්ථාවරත්වය සඳහා උදෑසන කියවීම් ගන්න',
        'Record location coordinates if possible': 'හැකි නම් ස්ථාන ඛණ්ඩාංක පටිගත කරන්න',
        'Take multiple readings and average them': 'බහු කියවීම් ගෙන ඒවා සාමාන්‍ය කරන්න',
        'Recent Data Entries': 'මෑත දත්ත ඇතුළත් කිරීම්',
        'Field': 'ක්ෂේත්‍රය',
        'Temp (°C)': 'උෂ්ණත්වය (°C)',
        'Time': 'වේලාව',
        'No data recorded yet': 'අතුරුදහන්',
        'Start by entering your first measurement above!': 'ඉහත ඔබේ පළමු මිනුම ඇතුළත් කිරීමෙන් ආරම්භ කරන්න!',
        'Why This Matters': 'මෙය ඇයි වැදගත්ද',
        'Crop Growth': 'බෝග වර්ධනය',
        'Optimal temperature ranges for different crops': 'විවිධ බෝග සඳහා ප්‍රශස්ත උෂ්ණත්ව පරාස',
        'Irrigation': 'වාරිමාර්ග',
        'Water needs vary with soil temperature': 'ජල අවශ්‍යතා පස උෂ්ණත්වය සමඟ වෙනස් වේ',
        'Fertilizer': 'සාර',
        'Nutrient uptake depends on soil conditions': 'පෝෂක ග්‍රහණය පස තත්වයන් මත රඳා පවතී',
        'Yield': 'ඵලදායිතාව',
        'Better data leads to better decisions': 'හොඳ දත්ත හොඳ තීරණවලට මග පාදයි',
        'Next Steps': 'ඊළඟ පියවර',
        'Record Data': 'දත්ත පටිගත කරන්න',
        'Input your measurements regularly': 'ඔබේ මිනුම් නිතිපතා ඇතුළත් කරන්න',
        'Get Insights': 'අවබෝධය ලබා ගන්න',
        'View personalized recommendations': 'පුද්ගලික නිර්දේශ බලන්න',
        'Track Progress': 'ප්‍රගතිය නිරීක්ෂණය කරන්න',
        'Monitor improvements over time': 'කාලයත් සමඟ වැඩිදියුණු වීම් නිරීක්ෂණය කරන්න',
        'Optimize': 'ප්‍රශස්ත කරන්න',
        'Apply insights for better yields': 'හොඳ ඵලදායිතාව සඳහා අවබෝධය යොදා ගන්න',
    }
}

@register.simple_tag(takes_context=True)
def custom_trans(context, text, language=None):
    """Custom translation tag that works without compiled .mo files"""
    if not language:
        # Get current language from session first, then from Django's translation system
        request = context.get('request')
        if request and hasattr(request, 'session'):
            language = request.session.get('django_language') or translation.get_language() or 'en'
        else:
            language = translation.get_language() or 'en'
    
    # Get translations for the current language
    lang_translations = TRANSLATIONS.get(language, TRANSLATIONS['en'])
    
    # Return translated text or original if not found
    return lang_translations.get(text, text)

@register.simple_tag(takes_context=True)
def custom_trans_simple(context, text, language=None):
    """Simple version that gets language from session"""
    if not language:
        # Get language from session first
        request = context.get('request')
        if request and hasattr(request, 'session'):
            language = request.session.get('django_language') or 'en'
        else:
            language = 'en'
    
    # Get translations for the current language
    lang_translations = TRANSLATIONS.get(language, TRANSLATIONS['en'])
    
    # Return translated text or original if not found
    return lang_translations.get(text, text)

@register.simple_tag
def get_current_language():
    """Get current language from session"""
    return translation.get_language() or 'en'
